### ISSUE TITLE
1.2 changes root node for XPath

### ISSUE THREAD

**Issue by artemyarulin** [graetzer/GDataXML-HTML#11]
Starting from v.1.2 xpath stopped returning current node after document creation. Well, it is easier to explain here:

```
    GDataXMLDocument* doc = [[GDataXMLDocument alloc] initWithXMLString:@"<doc/>" error:NULL];
    XCTAssertEqual([doc nodesForXPath:@"//doc" error:NULL].count,(NSUInteger)1,@"1.1: Works, 1.2: Works");
    XCTAssertEqual([doc nodesForXPath:@"/doc" error:NULL].count,(NSUInteger)1, @"1.1: Works, 1.2: Works");
    XCTAssertEqual([doc nodesForXPath:@"doc" error:NULL].count,(NSUInteger)1,  @"1.1: Works, 1.2: Fails");
```
 
Most probably it happened because of this commit: https://github.com/graetzer/GDataXML-HTML/commit/87ae11b09b7041195016d46f1a88f5368d23cd8e. As far as I understand it changes default root element.

**Comment by david-robles** [comment]
Hi there. Sorry I'm late to the party. It's unfortunate that you couldn't get the third example to work without casting _xmlDoc to xmlNodePtr. I did a bit of investigating myself and found several libraries that perform this cast roughly the same way this branch is doing it. I also found some [open source Apple code](http://www.opensource.apple.com/source/CPANInternal/CPANInternal-62/XML-LibXML/xpath.c) which uses xmlDocGetRootElement() when the xpath context node reference is the doc element itself, but only when handling the namespaces, again, roughly the same way this branch is working. This looks good to me.

**Comment by master-nevi** [comment]
Hi there. Sorry I'm late to the party. It's unfortunate that you couldn't get the third example to work without casting _xmlDoc to xmlNodePtr. I did a bit of investigating myself and found several libraries that perform this cast roughly the same way this branch is doing it. I also found some [open source Apple code](http://www.opensource.apple.com/source/CPANInternal/CPANInternal-62/XML-LibXML/xpath.c) which uses xmlDocGetRootElement() when the xpath context node reference is the doc element itself, but only when handling the namespaces, again, roughly the same way this branch is working. This looks good to me.

**Comment by artemyarulin** [comment]
@master-nevi Thank you for the investigation!
@graetzer What do you think? Can we merge a branch to master or you would like to wait until I check this update in real life to be sure that it doesn't cause any crashes?

**Comment by artemyarulin** [comment]
Hi again, any chance to get this merged to the master and release a new version to CocoaPods? I'm now creating [react-native-xml](https://github.com/artemyarulin/react-native-xml) and having a new version in CocoaPods would make my life easier!

Thanks!

**Comment by graetzer** [comment]
Just pushed 1.3.0 to cocoapods, should be fixed now
