### ISSUE TITLE
Crash with invalid xml

### ISSUE THREAD

**Issue by artemyarulin** [graetzer/GDataXML-HTML#14]
Following xml causing a crash:
```
<?xml version="1.0"?>
<!DOCTYPE EXAMPLE SYSTEM "example.dtd" [
<!ENTITY xml "<prefix:node>prefix is indeclared here</prefix:node>">
]>
<EXAMPLE xmlns:prefix="http://example.com">
  &xml;
</EXAMPLE>
```

Actually in debug version following assert https://github.com/graetzer/GDataXML-HTML/blob/master/Pod/Classes/GDataXMLNode.m#L375-L379 will fail:
```
- (NSString *)stringFromXMLString:(const xmlChar *)chars {
    
#if DEBUG
    NSCAssert(chars != NULL, @"GDataXMLNode sees an unexpected empty string");
#endif
    if (chars == NULL) return nil;
```

If we remove it (or use a release version) lib will crash later on in https://github.com/graetzer/GDataXML-HTML/blob/master/Pod/Classes/GDataXMLNode.m#L582-L586 in the `if` check:

```
  if (asprintf(&qname, "%s:%s", (const char *)xmlNode_->ns->prefix,
                         xmlNode_->name) != -1) {
                str = [self stringFromXMLString:(const xmlChar *)qname];
                free(qname);
            }
```

**Comment by artemyarulin** [comment]
Hm, looks like assert is not related - even if I disable it and return empty string instead of nil it will crash

**Comment by graetzer** [comment]
Can you print the content of ```xmlNode_->name``` or of ```xmlNode_->ns->prefix``` when you debug it in XCode? 

I guess one of these values has to be garbage, during debugging you could try the [command window](http://stackoverflow.com/a/15232304) to evaluate the expression ```strl(xmlNode_->ns->prefix)```

**Comment by artemyarulin** [comment]
I guess you meant `strlen`?

Here the output:
```
...
namespace warning : Namespace prefix prefix was not found
<prefix:node>prefix is indeclared here</prefix:node>
            ^

(lldb) po xmlNode_->ns->prefix
""
(lldb) po xmlNode_->name
"xml"
(lldb) po strl(xmlNode_->ns->prefix)
error: use of undeclared identifier 'strl'
error: 1 errors parsing expression
(lldb) po strlen(xmlNode_->name)
0x0000000000000003
(lldb) po strlen(xmlNode_->ns->prefix)
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).
The process has been returned to the state before expression evaluation.
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).
The process has been returned to the state before expression evaluation.
(lldb) print xmlNode_->ns->prefix
(const xmlChar *) $4 = 0x6572616c6365646e ""
(lldb) print xmlNode_->name
(const xmlChar *) $5 = 0x00007fb153921c28 "xml"
```

**Comment by graetzer** [comment]
I don't get it, how can strlen crash, but the debugger displays an empty string ?
Anyway it would be interesting to know where this value becomes corrupted

**Comment by artemyarulin** [comment]
I've created a branch `ns-crash` with test case which causes a crash, here the change: https://github.com/graetzer/GDataXML-HTML/commit/84fac869aa1341e3a5f120f3aed26df429a4942a

I'm recursively reading all the nodes in order to cause it

**Comment by graetzer** [comment]
So technically there is not much that happens inside the GDataXMLNode class right?
The [- (NSArray*)children](https://github.com/graetzer/GDataXML-HTML/blob/master/Pod/Classes/GDataXMLNode.m#L659) method extracts all the child nodes from the ```xmlNodePtr``` structure and wraps them in a ```GDataXMLNode``` object.

This could a bug in the libxml2 library or we're not allowed to use this field's value in this case. What's the value of ```xmlNode_->type``` where it crashes

**Comment by artemyarulin** [comment]
```
(lldb) po xmlNode_->name
"xml"

(lldb) po xmlNode_->type
XML_ENTITY_DECL
```

So yeah, I also wasn't able to find any code which creates this `ns->prefix` so I assume it is coming from libxml

**Comment by graetzer** [comment]
Maybe we should special handle it like the XML_NAMESPACE_DECL and just return the name?
Not sure what the proper qualified name is for an xml entity

**Comment by artemyarulin** [comment]
Yep it fixes a problem - I've created a pull request #15, have a look whenever you have time
